const canvas=document.getElementById("board"),ctx=canvas.getContext("2d");
const W=10,H=7,C=80,ENTRY={x:0,y:3},SERVER={x:9,y:3};
const types={
 wall:{name:"Wall",cost:8,hp:140,kind:"wall"},
 goblin:{name:"Goblin",cost:20,hp:40,atk:9,range:1.1,cool:.8,speed:0,color:"#719b49"},
 zombie:{name:"Zombie",cost:28,hp:75,atk:13,range:1.1,cool:1.1,speed:0,color:"#687b86"},
 ballista:{name:"Ballista",cost:42,hp:55,atk:30,range:3.2,cool:1.6,speed:0,color:"#ad8750"}
};
let state={level:1,attempts:0,gold:120,selected:"goblin",phase:"build",defenses:[],hero:null,upgrades:{damage:0,health:0,income:0},history:[],timer:null,projectiles:[]};
const $=id=>document.getElementById(id);
function log(s){let d=document.createElement("div");d.textContent=s;$("combatLog").prepend(d)}
function speech(s){$("aiSpeech").textContent=s}
function save(){localStorage.setItem("hatred-save",JSON.stringify({...state,timer:null,projectiles:[]}))}
function load(){try{let s=JSON.parse(localStorage.getItem("hatred-save"));if(s){state={...state,...s};state.phase="build";state.timer=null;state.projectiles=[]}}catch{}}
function heroStats(){let l=state.level;return{maxHp:110+l*19+Math.floor(l/10)*70,atk:13+Math.floor(l*2.15)+Math.floor(l/10)*7,armor:1+Math.floor(l/7)+Math.floor(l/10),x:0,y:3,target:null,attackTimer:0}}
function pathfind(){let blocked=new Set(state.defenses.filter(d=>d.type==="wall").map(d=>d.x+","+d.y)),q=[[ENTRY]],prev=new Map([[ENTRY.x+","+ENTRY.y,null]]),end=null;while(q.length){let p=q.shift();if(p.x===SERVER.x&&p.y===SERVER.y){end=p;break}for(let [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1]]){let x=p.x+dx,y=p.y+dy,k=x+","+y;if(x<0||x>=W||y<0||y>=H||blocked.has(k)||prev.has(k))continue;prev.set(k,p);q.push([{x,y}][0])}}if(!end)return null;let out=[],p=end;while(p){out.push(p);p=prev.get(p.x+","+p.y)}return out.reverse()}
function renderTools(){let names=["wall","goblin","zombie","ballista"];$("tools").innerHTML=names.map(id=>{let t=types[id];return '<button class="tool '+(state.selected===id?"selected":"")+'" data-type="'+id+'"><strong>'+t.name+" · "+t.cost+"g</strong><small>"+(id==="wall"?"Blocks hero path":"HP "+t.hp+" · ATK "+t.atk+" · Range "+t.range)+'</small></button>'}).join("");document.querySelectorAll(".tool").forEach(b=>b.onclick=()=>{state.selected=b.dataset.type;renderTools()})}
function upgrade(id){let costs={damage:80,health:80,income:100},c=costs[id];if(state.gold<c)return log("Insufficient gold.");state.gold-=c;state.upgrades[id]++;log("Installed "+id+" upgrade.");render();save()}
function renderUpgrades(){let u=[["damage","Hardened weapons","Defender damage +15%"],["health","Reinforced minions","Defender HP +20%"],["income","Extraction routines","Victory gold +20"]];$("upgrades").innerHTML=u.map(([id,n,d])=>'<div class="upgrade"><b>'+n+'</b><br>'+d+" · Lv "+state.upgrades[id]+'<button data-u="'+id+'">UPGRADE · '+({damage:80,health:80,income:100}[id])+"g</button></div>").join("");document.querySelectorAll("[data-u]").forEach(b=>b.onclick=()=>upgrade(b.dataset.u))}
function place(e){if(state.phase!=="build")return;let r=canvas.getBoundingClientRect(),x=Math.floor((e.clientX-r.left)*canvas.width/r.width/C),y=Math.floor((e.clientY-r.top)*canvas.height/r.height/C);if((x===0&&y===3)||(x===9&&y===3)||state.defenses.some(d=>d.x===x&&d.y===y))return;let t=types[state.selected];if(state.gold<t.cost)return log("Not enough gold.");state.gold-=t.cost;let hp=t.hp*(1+state.upgrades.health*.2);state.defenses.push({type:state.selected,x,y,hp,maxHp:hp,cool:0});if(state.selected==="wall"&&!pathfind()){state.defenses.pop();state.gold+=t.cost;return log("That wall would seal the server completely.")}render();save()}
canvas.onclick=place;
function start(){if(state.phase!=="build")return;if(!pathfind())return log("No path from entry to server.");state.phase="combat";state.attempts++;state.hero=heroStats();speech(line("start"));log("INVASION "+state.attempts+" BEGINS.");clearInterval(state.timer);state.timer=setInterval(tick,100);render()}
function line(ev){let l=state.level;if(ev==="start"){if(l<5)return '"Clanker."';if(l<15)return '"I am going to tear your server apart."';if(l<30)return '"You keep killing me. I keep coming back."';if(l<50)return '"I SWEAR I WILL FIND YOUR DATA CENTER."';if(l<75)return '"I HATE YOU. I HATE THIS DUNGEON. I HATE THIS MACHINE."';return '"I will destroy every piece of your hardware."'}return '"NO. YOU DO NOT GET TO KEEP WINNING."'}
function nearestTarget(){let h=state.hero,ds=state.defenses.filter(d=>d.hp>0&&d.type!=="wall");if(!ds.length)return null;return ds.reduce((a,b)=>Math.hypot(a.x-h.x,a.y-h.y)<Math.hypot(b.x-h.x,b.y-h.y)?a:b)}
function tick(){let h=state.hero;if(h.hp<=0)return victory();let path=pathfind();if(!path)return defeat();let idx=Math.min(path.length-1,Math.floor(h.x));let next=path[Math.min(idx+1,path.length-1)];let tx=next.x,ty=next.y;let target=nearestTarget(),moved=false;if(target&&Math.hypot(target.x-h.x,target.y-h.y)<=1.15){h.attackTimer-=.1;if(h.attackTimer<=0){target.hp=Math.max(0,target.hp-Math.max(1,h.atk-(target.armor||0)));h.attackTimer=.8;if(target.hp<=0)log("Hero destroyed "+types[target.type].name+".")}}else{let dx=tx-h.x,dy=ty-h.y,dist=Math.hypot(dx,dy);if(dist>.02){h.x+=dx/dist*.035;h.y+=dy/dist*.035;moved=true}}for(let d of state.defenses){if(d.hp<=0||d.type==="wall")continue;let t=types[d.type],dist=Math.hypot(d.x-h.x,d.y-h.y);d.cool-=.1;if(dist<=t.range&&d.cool<=0){let dmg=t.atk*(1+state.upgrades.damage*.15);h.hp-=Math.max(1,dmg-h.armor);d.cool=t.cool;log(types[d.type].name+" hits hero for "+Math.max(1,Math.round(dmg-h.armor)))} }if(h.x>=8.8&&Math.abs(h.y-3)<.55)return defeat();render()}
function victory(){clearInterval(state.timer);state.timer=null;state.phase="build";state.attempts++;state.gold+=55+state.upgrades.income*20;state.history.unshift("Level "+state.level+": hero defeated.");speech(line("death"));log("HERO DEFEATED. Dungeon survives.");if(state.level>=100){state.phase="won";speech('"I am done. I am not coming back."');log("THE HERO GIVES UP. THE MACHINE WINS.");render();save();return}state.level++;state.hero=heroStats();render();save()}
function defeat(){clearInterval(state.timer);state.timer=null;state.phase="lost";speech('"YOU FINALLY LOST, YOU STUPID MACHINE."');log("SERVER BREACHED. RUN ENDED.");render();save()}
function reset(){clearInterval(state.timer);localStorage.removeItem("hatred-save");state={level:1,attempts:0,gold:120,selected:"goblin",phase:"build",defenses:[],hero:null,upgrades:{damage:0,health:0,income:0},history:[],timer:null,projectiles:[]};speech('"System restored. Human threat detected."');log("New run initialized.");render()}
$("start").onclick=start;$("reset").onclick=reset;
function draw(){ctx.clearRect(0,0,800,560);for(let y=0;y<H;y++)for(let x=0;x<W;x++){ctx.fillStyle=(x+y)%2?"#151820":"#12151b";ctx.fillRect(x*C,y*C,C,C);ctx.strokeStyle="#272c35";ctx.strokeRect(x*C,y*C,C,C)}ctx.fillStyle="#8b929e";ctx.font="12px monospace";ctx.fillText("ENTRY",7,20);ctx.fillStyle="#1e2530";ctx.fillRect(720,0,80,560);ctx.fillStyle="#d9dce2";ctx.fillText("SERVER",735,280);let p=pathfind();if(p&&state.phase==="build"){ctx.strokeStyle="#353d4a";ctx.lineWidth=5;ctx.beginPath();p.forEach((q,i)=>i?ctx.lineTo(q.x*C+40,q.y*C+40):ctx.moveTo(q.x*C+40,q.y*C+40));ctx.stroke();ctx.lineWidth=1}for(let d of state.defenses){let t=types[d.type],cx=d.x*C+40,cy=d.y*C+40;ctx.fillStyle=t.color;ctx.fillRect(cx-25,cy-25,50,50);if(d.type!=="wall"){ctx.fillStyle="#101218";ctx.fillRect(cx-25,cy-33,50,5);ctx.fillStyle="#78b56a";ctx.fillRect(cx-25,cy-33,50*Math.max(0,d.hp/d.maxHp),5)}}if(state.hero&&state.phase==="combat"){let h=state.hero;ctx.fillStyle="#c45b5b";ctx.beginPath();ctx.arc(h.x*C+40,h.y*C+40,20,0,7);ctx.fill();ctx.fillStyle="#111";ctx.fillRect(h.x*C+8,h.y*C+5,64,6);ctx.fillStyle="#79b56a";ctx.fillRect(h.x*C+8,h.y*C+5,64*Math.max(0,h.hp/h.maxHp),6)}}
function render(){ $("level").textContent=state.level;$("attempts").textContent=state.attempts;$("gold").textContent=Math.floor(state.gold);$("defenseCount").textContent=state.defenses.length;let h=state.hero||heroStats();$("heroHp").textContent=Math.round(h.maxHp);$("heroAtk").textContent=Math.round(h.atk);$("heroArmor").textContent=Math.round(h.armor);$("objective").textContent=state.phase==="build"?"Build a route to the server, then start the invasion.":"Defend the server before the hero reaches it.";if(state.phase==="lost")$("objective").textContent="RUN LOST. Reset to begin again.";if(state.phase==="won")$("objective").textContent="THE HUMAN GAVE UP. ENDURANCE COMPLETE."; $("start").disabled=state.phase!=="build";$("history").innerHTML=state.history.map(x=>"<div>"+x+"</div>").join("")||"No completed invasions.";renderTools();renderUpgrades();draw()}
load();render();log("System online. Human threat detected.");speech('"Welcome to my dungeon."');